# Generated by Django 6.0 on 2026-01-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_is_favorited_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(related_name='in_shopping_carts', to='recipes.recipe'),
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
    ]
